In [ ]:
import numpy as np


arr1 = np.array([1,2,3,4,5])
print(arr1)

<class 'numpy.ndarray'>


In [6]:
arr2 = np.array([1,2,3,4,5],[6,7,4,5,3])
arr2.reshape(1,5) ##1 row and 5 columns

array([[1, 2, 3, 4, 5]])

In [50]:
arr3 = np.array([[1,2,3,4,5],[6,7,4,5,3]])
print(arr3.shape)
print(arr3.ndim) ##Dimention
print(arr3.size)
print(arr3.dtype)
print(arr3.itemsize) ##Bit size

(2, 5)
2
10
int64
8


In [51]:
np.arange(0,10,2).reshape(1,5)

array([[0, 2, 4, 6, 8]])

In [52]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [53]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [57]:
## Vectorized operation

arr1 = np.array([1,2,3,8,5])
arr2 = np.array([2,3,4,5,9])

print(arr1+arr2)

print(arr1-arr2)

print(arr1*arr2)

print(arr1/arr2)

[ 3  5  7 13 14]
[-1 -1 -1  3 -4]
[ 2  6 12 40 45]
[0.5        0.66666667 0.75       1.6        0.55555556]


In [58]:
## Universal functions
arr = np.array([2,3,4,5,9])

print(np.sqrt(arr))

print(np.exp(arr))

print(np.sin(arr))

print(np.log(arr))




[1.41421356 1.73205081 2.         2.23606798 3.        ]
[7.38905610e+00 2.00855369e+01 5.45981500e+01 1.48413159e+02
 8.10308393e+03]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427  0.41211849]
[0.69314718 1.09861229 1.38629436 1.60943791 2.19722458]


In [79]:
##Array slicing and indexing

arr = np.array([[1,2,4,5,7],[3,6,7,3,6],[4,3,7,1,5]])
print(arr)
print("Pickup element")
print(arr[1][4])
print(arr[0:4,2:4])



[[1 2 4 5 7]
 [3 6 7 3 6]
 [4 3 7 1 5]]
Pickup element
6
[[4 5]
 [7 3]
 [7 1]]


In [80]:
##modify elemet

arr[0][0] = 100
print(arr)

[[100   2   4   5   7]
 [  3   6   7   3   6]
 [  4   3   7   1   5]]


In [86]:
##Logical concepts

data = np.array([1,2,3,4,5,6,7,8,9])
data>5
data[data>3]
data[(data>5) & (data<=9)]


array([6, 7, 8, 9])